In [1]:
import numpy as np

In [3]:
matrix1=np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
matrix2=np.array([[9,7,5],
                  [8,6,4],
                  [2,4,6]])

In [5]:
print("matrix 1:")
print(matrix1)

matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print("matrix 2:")
print(matrix2)

matrix 2:
[[9 7 5]
 [8 6 4]
 [2 4 6]]


In [9]:
add=matrix1+matrix2
print(add)

[[10  9  8]
 [12 11 10]
 [ 9 12 15]]


In [11]:
sub=matrix1-matrix2
print(sub)

[[-8 -5 -2]
 [-4 -1  2]
 [ 5  4  3]]


In [13]:
mult=matrix1*matrix2
print(mult)

[[ 9 14 15]
 [32 30 24]
 [14 32 54]]


In [15]:
dot=np.dot(matrix1,matrix2)
print(dot)

[[ 31  31  31]
 [ 88  82  76]
 [145 133 121]]


In [17]:
trans=np.transpose(matrix1)
print(trans)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [19]:
det=np.linalg.det(matrix1)
print(det)

6.66133814775094e-16


In [21]:
matrix_a=np.random.randint(1,10,(3,3))
matrix_b=np.random.randint(1,10,(3,3))
print(matrix_a)
print(matrix_b)

[[1 3 8]
 [9 7 8]
 [9 9 9]]
[[9 8 3]
 [9 2 1]
 [6 8 6]]


In [23]:
det1=np.linalg.det(matrix_a)
print(matrix_a)

[[1 3 8]
 [9 7 8]
 [9 9 9]]


In [25]:
if det1 !=0:
    inverse_a=np.linalg.inv(matrix_a)
    print(inverse_a)
else:
    print("not have an inverse")

[[-0.08333333  0.41666667 -0.2962963 ]
 [-0.08333333 -0.58333333  0.59259259]
 [ 0.16666667  0.16666667 -0.18518519]]


In [27]:
sine=np.sin(matrix_a)
print(sine)

[[0.84147098 0.14112001 0.98935825]
 [0.41211849 0.6569866  0.98935825]
 [0.41211849 0.41211849 0.41211849]]


In [29]:
log=np.log(matrix_a,where=matrix_a >0)
print(log)

[[0.         1.09861229 2.07944154]
 [2.19722458 1.94591015 2.07944154]
 [2.19722458 2.19722458 2.19722458]]


In [31]:
diag=np.diagonal(matrix_a)
row_1=matrix_a[0,:]
elements_greater_than_5=matrix_a[matrix_a>5]
print(diag)
print(row_1)
print(elements_greater_than_5)

[1 7 9]
[1 3 8]
[8 9 7 8 9 9 9]


In [ ]:
import numpy as np
class GuessGame:
    def __init__(self):
        self.number_to_guess=np.random.randint(1, 101)
        self.guess_count=0
    def play(self):
        print("welcome to the Guess Game")
        print("I will taking a number between 1 and 100. can you guess it?!")
        while True:
            try:
                player_guess=int(input("Enter your guess: "))
                self.guess_count+=1
                if player_guess < self.number_to_guess:
                    print("too low! Try again :) ")
                elif player_guess > self.number_to_guess:
                    print("too high! Try again :) ")
                else:
                    print("Bravo!! you got it :D ")
                    break
            except ValueError:
                print("please inter a number")
game=GuessGame()
game.play()                

welcome to the Guess Game
I will taking a number between 1 and 100. can you guess it?!


Enter your guess:  


please inter a number


In [ ]:
import numpy as np
 
class GuessTheNumber:
    def __init__(self):
        self.target_number = 0    
        self.attempts = 0       
 
    def generate_number(self):
        self.target_number = np.random.randint(1, 101)
        print("!")
 
    def check_guess(self, guess):
        self.attempts += 1   
        if guess < self.target_number:
            print("اTRY AGIN THE NUM IS LOW ")
        elif guess > self.target_number:
            print("اTRY AGIN THE NUM IS HIGH !")
        else:
            print(f"  BRAVOO ({self.target_number}) في {self.attempts} محاولة.")
 
    def play(self):
        self.generate_number()
        while True:
            try:
                guess = int(input(" PLESE ENTER THEN GUSSE NUM ( 1 , 100): "))
                if guess < 1 or guess > 100:
                    print("   PLESE ENTER THE NUM FROM  1 , 100.")
                    continue
                # اVEIVY FROM GUSSE
                self.check_guess(guess)
                if guess == self.target_number:
                    break  # END THE PLAY 
            except ValueError:
                print("   PLEASE ENTER THE CORECT NUM.")
 
 
if __name__ == "__main__":
    game = GuessTheNumber()  
    game.play()

In [5]:
import numpy as np
grades = np.array([
    [85, 90, 78],  #1:Math, Science, English
    [88, 76, 92],  #2:Math, Science, English
    [90, 88, 84],  #3:Math, Science, English
    [72, 85, 80],  #4:Math, Science, English
    [95, 91, 89]   #5:Math, Science, English
])
average_per_student = np.mean(grades, axis=1)

average_per_subject = np.mean(grades, axis=0)

highest_per_subject = np.max(grades, axis=0)
lowest_per_subject = np.min(grades, axis=0)

std_dev_per_subject = np.std(grades, axis=0)

print("Average grade for each student:", average_per_student)
print("Average grade for each subject:", average_per_subject)
print("Highest grade in each subject:", highest_per_subject)
print("Lowest grade in each subject:", lowest_per_subject)
print("Standard deviation of grades for each subject:", std_dev_per_subject)

Average grade for each student: [84.33333333 85.33333333 87.33333333 79.         91.66666667]
Average grade for each subject: [86.  86.  84.6]
Highest grade in each subject: [95 91 92]
Lowest grade in each subject: [72 76 78]
Standard deviation of grades for each subject: [7.72010363 5.40370243 5.27636238]


In [31]:
import numpy as np
my_array = np.array([1, 2, 2, 3, 4, 4, 4, 5])
UN, counts = np.unique(my_array, return_counts=True)
duplicates = UN[counts > 1]
counts1 = np.bincount(my_array)
alaa=my_array.flatten()
print("THE NUM IS DUB", duplicates)
print(counts1)
print(alaa)

THE NUM IS DUB [2 4]
[0 1 2 1 3 1]
[1 2 2 3 4 4 4 5]


In [19]:
import numpy as np
 
my_array = np.array([1, 2, 2, 3, 4, 4, 4, 5])
 
counts = np.bincount(my_array)
 
duplicates = np.where(counts > 1)[0]
 
print(" THE NUM IS ", duplicates)

 THE NUM IS  [2 4]
